
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_nyman_enchant_kotlin_Greeter */

#ifndef _Included_dev_nyman_enchant_kotlin_Greeter
#define _Included_dev_nyman_enchant_kotlin_Greeter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:	 dev_nyman_enchant_kotlin_Greeter
 * Method:	sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dev_nyman_enchant_kotlin_Greeter_sayHello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
